---
title: "p8105_hw1_lt2949"
output: github_document
date: "2023-09-20"
---

```{r}
library(tidyverse)

data("early_january_weather")
early_january_weather

str(early_january_weather)
nrow(early_january_weather)
ncol(early_january_weather)
mean(early_january_weather$temp)
ggplot(early_january_weather, aes(x = time_hour, y = temp, color = humid)) + geom_point()
ggsave("scatter_plot.pdf", height = 4, width = 6)

##The dataset consists of 358 observations spread across 15 columns, with an average temperature of 39.58 degree Farenheit. Among these 15 attributes, we have "temp" indicating the temperature in degrees Fahrenheit at the corresponding hour. "humid" provides the humidity level for that hour. "time_hour" denotes the exact hour of the observation, and "Wind_speed" specifies the wind speed at that particular hour.
```
```{r}
sample <- rnorm(10)
df <- data.frame(
  sample,
  log_vector = sample > 0,
  char_vector = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
  fact_vector = factor(rep(1:3, length.out = 10))
)

print(df)
mean_sample <- mean(pull(df, sample))
mean_sample
mean_log <- mean(pull(df, log_vector))
mean_log
```

